name: Java Unit Test Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 19
        distribution: hotspot
    - name: Build and test
      run: |
        ./gradlew build
        ./gradlew test
