name: Java Unit Test Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK - AdoptOpenJDK
      uses: actions/setup-java@v2
      with:
        java-version: 14
        distribution: adopt
#    - name: Lint code
#      run: gradle lint
#    - name: code smell + cyclomatic complexity
#      run: gradle checkstyleMain checkstyleTest
    - name: Build and test
      run: gradle build test
    - name: Check code quality
      run: gradle checkstyleMain
      if: failure()
      env:
        GRADLE_OPTS: "-Xmx256m"

